name: publish

on: [push]

jobs:
  publish-go-web-app-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the go-web-app image
      run: |
        docker build . --tag ghcr.io/Anugopinathan/go-web-app:latest
        docker run ghcr.io/Anugopinathan/go-web-app:latest
        docker push ghcr.io/Anugopinathan/go-web-app:latest

